osx_defaults:
  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    notify: "Restart Dock"

  - domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
    notify: "Restart Dock"

  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.dock
    key: autohide
    type: bool
    value: true
    notify: "Restart Dock"

  - domain: com.apple.dock
    key: autohide-delay
    type: float
    value: 0
    notify: "Restart Dock"

  - domain: NSGlobalDomain
    key: AppleShowAllExtensions
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.finder
    key: AppleShowAllFiles
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.finder
    key: ShowPathBar
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.desktopservices
    key: DSDontWriteNetworkStores
    type: bool
    value: true
    notify: "Restart Finder"

  - domain: com.apple.dock
    key: persistent-apps
    type: array
    value: []
    notify: "Restart Dock"

  - domain: com.apple.dock
    key: wvous-tl-corner
    type: int
    value: 10
    notify: "Restart Dock"

  - domain: com.apple.dock
    key: wvous-tl-modifier
    type: int
    value: 0
    notify: "Restart Dock"

  - domain: com.apple.menuextra.battery
    key: ShowPercent
    type: bool
    value: true

  - domain: com.apple.menuextra.clock
    key: DateFormat
    type: string
    value: "M\u6708d\u65e5(EEE) H:mm"

  - domain: com.apple.screencapture
    key: location
    type: string
    value: "~/Pictures/ss/"

  - domain: com.apple.screencapture
    key: disable-shadow
    type: bool
    value: true

  - domain: NSGlobalDomain
    key: NSAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

  - domain: NSGlobalDomain
    key: WebAutomaticSpellingCorrectionEnabled
    type: bool
    value: false

  - domain: com.apple.inputmethod.Kotoeri
    key: JIMPrefCandidateWindowFontKey
    type: string
    value: "HiraginoSans-W3"



  

