---
- name: modify .zprofile for node
  lineinfile:
    dest: ~/.zprofile
    state: present
    line: "{{ item.line }}"
  with_items:
    - "{{ modify_zprofile_for_node }}"

- name: Check node version
  shell: |
      node -v
  register: res
  failed_when: no
  changed_when: res.rc != 0
  notify:
    - Install nodejs
